[package]
name = "rust_template_gui"
version = "0.1.0"
edition = "2024"

authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
rust_template_core = { path = "../core" }
rust_template_interface = { path = "interface" }
rust_template_render = { path = "render" }
tracing = "0.1"
