[workspace]
members = [
    "crates/cli",
    "crates/gui",
]

resolver = "2"

[workspace.package]
authors = ["Marco Ramos <marcoandreramos17@gmail.com>"]
license = "MIT"
repository = "https://github.com/marcoramos17/rust-template"
homepage = "https://marcoramos17.github.io/rust-template"
documentation = "https://marcoramos17.github.io/rust-template"
