[package]
name = "rust_template_interface"
version = "0.1.0"
edition = "2024"

authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
egui = { version = "0.28.1", default-features = false, features = ["default_fonts"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
