[package]
name = "rust_template_render"
version = "0.1.0"
edition = "2024"

authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
rust_template_core = { path = "../../core" }
winit = "0.31.0-beta.1"
wgpu = "0.20"
egui = { version = "0.28.1", default-features = false, features = ["default_fonts"] }
egui-wgpu = { version = "0.28.1", default-features = false }
web-time = "0.2"
pollster = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
